[package]
name = "ar-hist"
version = "0.1.0"
authors = ["av_elier <adelier1111@gmail.com>"]

[dependencies]
redis = "0.8.0"
url = "1.6.0"
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
serde = "1.0.8"
serde_json = "1.0.8"
serde_derive = "1.0.8"
chrono = "0.4.0"
postgres = "0.15.1"
